// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package entity

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	Id        pgtype.UUID
	Name      string
	Age       int32
	CreatedAt pgtype.Timestamptz
}

type Book struct {
	Id          pgtype.UUID
	Title       string
	AuthorId    pgtype.UUID
	PublishedAt pgtype.Date
	CreatedAt   pgtype.Timestamptz
}

type Label struct {
	Id        pgtype.UUID
	Title     string
	AuthorId  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Review struct {
	Id           pgtype.UUID
	BookId       pgtype.UUID
	Rating       int32
	Comment      pgtype.Text
	ReviewerName pgtype.Text
	CreatedAt    pgtype.Timestamptz
}
