// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authors.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sqlc-dev/sqlc-gen-go/example/sqlcout/entity"
)

// GetAuthorsGroup represents grouped data for GetAuthorsGroup
type GetAuthorsGroup struct {
	Id     pgtype.UUID   ``
	Name   string        ``
	Age    int32         ``
	Book   entity.Book   ``
	Review entity.Review ``

	// Nested fields
	Publications []*GetAuthorBook `json:"Publications"`
	AuthorLabels []*entity.Label  `json:"AuthorLabels"`
}

// GetAuthorBook represents grouped data for GetAuthorBook
type GetAuthorBook struct {

	// Nested fields
}

// GetAuthorGroup represents grouped data for GetAuthorGroup
type GetAuthorGroup struct {
	Id     pgtype.UUID   ``
	Name   string        ``
	Age    int32         ``
	Book   entity.Book   ``
	Review entity.Review ``

	// Nested fields
	Books        []*GetAuthorBook `json:"Books"`
	AuthorLabels []*entity.Label  `json:"AuthorLabels"`
}

// GetAuthorBook represents grouped data for GetAuthorBook
type GetAuthorBook struct {

	// Nested fields
}

// GetBooksGroup represents grouped data for GetBooksGroup
type GetBooksGroup struct {
	Id          pgtype.UUID        ``
	Title       string             ``
	AuthorId    pgtype.UUID        ``
	PublishedAt pgtype.Date        ``
	CreatedAt   pgtype.Timestamptz ``
	Review      entity.Review      ``
	Label       entity.Label       ``

	// Nested fields
	Books []*GetAuthorBook `json:"Books"`
}

// GetAuthorBook represents grouped data for GetAuthorBook
type GetAuthorBook struct {

	// Nested fields
}
