// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: books.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sqlc-dev/sqlc-gen-go/example/sqlcout/entity"
)

const getBooks = `-- name: GetBooks :many
SELECT 
    b.id, b.title, b.author_id, b.published_at, b.created_at,
    r.id, r.book_id, r.rating, r.comment, r.reviewer_name, r.created_at,
    l.id, l.title, l.author_id, l.created_at
FROM books b
LEFT JOIN labels l ON l.author_id = a.id
LEFT JOIN reviews r ON r.book_id = b.id
ORDER BY b.title, r.created_at
`

type GetBooksRow struct {
	ID          pgtype.UUID
	Title       string
	AuthorID    pgtype.UUID
	PublishedAt pgtype.Date
	CreatedAt   pgtype.Timestamptz
	Review      entity.Review
	Label       entity.Label
}

func (q *Queries) GetBooks(ctx context.Context) ([]*GetBooksRow, error) {
	rows, err := q.db.Query(ctx, getBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetBooksRow
	for rows.Next() {
		var i GetBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.Review.ID,
			&i.Review.BookID,
			&i.Review.Rating,
			&i.Review.Comment,
			&i.Review.ReviewerName,
			&i.Review.CreatedAt,
			&i.Label.ID,
			&i.Label.Title,
			&i.Label.AuthorID,
			&i.Label.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
